//
//  CharacterRepository.swift
//  AvengersApp
//
//  Created by Gustavo A Ramírez Franco on 4/12/20.
//

import Foundation

class CharacterRepository {
    
    func getAllSuperheroes() -> Superheroes {
        return [
            Superhero(image: "img_heroe_america_captain", name: "Captain America", powerScore: 4, description: "Captain America is a superhero appearing in American comic books published by Marvel Comics. Created by cartoonists Joe Simon and Jack Kirby, the character first appeared in Captain America Comics #1 (cover dated March 1941) from Timely Comics, a predecessor of Marvel Comics. Captain America was designed as a patriotic supersoldier who often fought the Axis powers of World War II and was Timely Comics' most popular character during the wartime period. The popularity of superheroes waned following the war, and the Captain America comic book was discontinued in 1950, with a short-lived revival in 1953. Since Marvel Comics revived the character in 1964, Captain America has remained in publication."),
            
            Superhero(image: "img_heroe_black_panther", name: "Black Panther", powerScore: 3, description: "Black Panther is a fictional superhero appearing in American comic books published by Marvel Comics. The character was created by writer-editor Stan Lee and writer-artist Jack Kirby, first appearing in Fantastic Four #52 (cover-dated July 1966) in the Silver Age of Comic Books. Black Panther's real name is T'Challa, and he is depicted as the king and protector of the fictional African nation of Wakanda. Along with possessing enhanced abilities achieved through ancient Wakandan rituals of drinking the essence of the heart-shaped herb, T'Challa also relies on his proficiency in science, rigorous physical training, hand-to-hand combat skills, and access to wealth and advanced Wakandan technology to combat his enemies."),
            
            Superhero(image: "img_heroe_black_widow", name: "Black Widow", powerScore: 2, description: "Black Widow (Natasha Romanova) is a fictional superhero appearing in American comic books published by Marvel Comics. Created by editor and plotter Stan Lee, scripter Don Rico, and artist Don Heck, the character debuted in Tales of Suspense #52 (April 1964). The character was introduced as a Russian spy, an antagonist of the superhero Iron Man. She later defected to the United States, becoming an agent of the fictional spy agency S.H.I.E.L.D. and a member of the superhero team the Avengers."),
            
            Superhero(image: "img_heroe_dr_strange", name: "Dr. Strange", powerScore: 4, description: "Doctor Stephen Strange is a fictional character appearing in American comic books published by Marvel Comics. Created by artist Steve Ditko and writer Stan Lee,[5] the character first appeared in Strange Tales #110 (cover-dated July 1963). Doctor Strange serves as the Sorcerer Supreme, the primary protector of Earth against magical and mystical threats. Inspired by stories of black magic and Chandu the Magician, Strange was created during the Silver Age of Comic Books to bring a different kind of character and themes of mysticism to Marvel Comics."),
            
            Superhero(image: "img_heroe_gamora", name: "Gamora", powerScore: 3, description: "Gamora Zen Whoberi Ben Titan is a fictional character appearing in American comic books published by Marvel Comics. Created by writer/artist Jim Starlin, the character first appeared in Strange Tales #180 (June 1975). Gamora is the adopted daughter of Thanos, and the last of her species. Her powers include superhuman strength and agility and an accelerated healing factor. She also is an elite combatant, being able to beat most of the opponents in the galaxy. She is a member of the group known as the Infinity Watch. The character played a role in the 2007 crossover comic book event 'Annihilation: Conquest', and became a member of the titular team in its spin-off comic, Guardians of the Galaxy."),
            
            Superhero(image: "img_heroe_hulk", name: "Hulk", powerScore: 4, description: "The Hulk is a fictional superhero appearing in publications by the American publisher Marvel Comics. Created by writer Stan Lee and artist Jack Kirby, the character first appeared in the debut issue of The Incredible Hulk (May 1962). In his comic book appearances, the character is both the Hulk, a green-skinned, hulking and muscular humanoid possessing a vast degree of physical strength, and his alter ego Dr. Robert Bruce Banner, a physically weak, socially withdrawn, and emotionally reserved physicist. The two exist as independent dissociative personalities, and resent each other."),
            
            Superhero(image: "img_heroe_ironman", name: "Ironman", powerScore: 5, description: "Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics. The character was co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby. The character made his first appearance in Tales of Suspense #39 (cover dated March 1963), and received his own title in Iron Man #1 (May 1968). Also in 1963, the character founded the Avengers alongside Thor, Ant-Man, Wasp and the Hulk."),
            
            Superhero(image: "img_heroe_marvel_captain", name: "Captain Marvel", powerScore: 5, description: "Carol Susan Jane Danvers is a fictional superhero appearing in American comic books published by Marvel Comics. Created by writer Roy Thomas and artist Gene Colan, Danvers first appeared as an officer in the United States Air Force and a colleague of the Kree superhero Mar-Vell in Marvel Super-Heroes #13 (March 1968). Danvers later became the first incarnation of Ms. Marvel in Ms. Marvel #1 (cover-dated Jan. 1977) after her DNA was fused with Mar-Vell's during an explosion, giving her superhuman powers. Debuting in the Silver Age of comics, the character was featured in a self-titled series in the late 1970s before becoming associated with the superhero teams the Avengers and the X-Men."),
            
            Superhero(image: "img_heroe_spiderman", name: "Spiderman", powerScore: 4, description: "Spider-Man is a fictional superhero created by writer-editor Stan Lee and writer-artist Steve Ditko. He first appeared in the anthology comic book Amazing Fantasy #15 (Aug. 1962) in the Silver Age of Comic Books. He appears in American comic books published by Marvel Comics, as well as in a number of movies, television shows, and video game adaptations set in the Marvel Universe. In the stories, Spider-Man is the alias of Peter Parker, an orphan raised by his Aunt May and Uncle Ben in New York City after his parents Richard and Mary Parker died in a plane crash."),
            
            Superhero(image: "img_heroe_thor", name: "Thor", powerScore: 5, description: "Thor Odinson is a fictional superhero appearing in American comic books published by Marvel Comics. The character, which is based on the Norse deity of the same name, is the Asgardian god of thunder who possesses the enchanted hammer, Mjolnir, which grants him the ability to fly and manipulate weather amongst his other superhuman attributes.")
            
        ]
    }
    
    func getAllVillians() -> Villians {
        return [
            Villian(image: "img_villan_dormammu", name: "Dormammu", powerScore: 5, description: "Dormammu is a fictional character appearing in American comic books published by Marvel Comics. The character first appeared in Strange Tales #126 (November 1964), and was created by Stan Lee and Steve Ditko."),
            
            Villian(image: "img_villan_ego", name: "Ego", powerScore: 2, description: "Ego the Living Planet is a fictional character appearing in American comic books published by Marvel Comics. The character first appeared in Thor #132 (September 1966) and was created by Jack Kirby."),
            
            Villian(image: "img_villan_hela", name: "Hela", powerScore: 5, description: "Hela is a fictional character appearing in American comic books published by Marvel Comics. The Asgardian goddess of death is based on the Norse goddess Hel. The ruler of Hel and Niflheim, the character has been a frequent foe of Thor. Debuting in the Silver Age of comic books, Hela first appeared in Journey into Mystery #102 and was adapted from Norse mythology by editor/writer Stan Lee and artist/writer Jack Kirby."),
            
            Villian(image: "img_villan_ivan_vanko", name: "Ivan Vanko", powerScore: 2, description: "Ivan Antonovich Vanko, an original character based on Whiplash and the Crimson Dynamo, and the son of Anton Vanko in the live-action Marvel Cinematic Universe film, Iron Man 2."),
            
            Villian(image: "img_villan_johann_schmidt", name: "Johann Schmidt", powerScore: 3, description: "The Red Skull is an alias used by several fictional supervillains appearing in American comic books published by Marvel Comics, primarily Johann Schmidt. The first Red Skull appeared in Captain America Comics #1 (March 1941), created by Joe Simon and Jack Kirby.[1] Usually portrayed as a Nazi agent and protégé of Adolf Hitler who is disfigured or wearing a red skull mask, the Red Skull is regarded as the archenemy of the superhero Captain America."),
            
            Villian(image: "img_villan_malekith", name: "Malekith", powerScore: 3, description: "Malekith is a fictional character appearing in American comic books published by Marvel Comics. He is the ruler of the Dark Elves of Svartalfheim, and has come into conflict with Thor. He once wielded the Casket of Ancient Winters."),
            
            Villian(image: "img_villan_ronan", name: "Ronan", powerScore: 3, description: "Ronan the Accuser is a fictional character appearing in American comic books published by Marvel Comics. Ronan was created by writer Stan Lee and artist Jack Kirby and he first appeared in Fantastic Four #65 (August 1967).[1] He is the Supreme Accuser of the Kree Empire, the militaristic government of the fictional alien race known as the Kree, and is commonly depicted as an adversary of superhero teams such as the Fantastic Four, the Avengers, and the Guardians of the Galaxy. In later years, the character was depicted as a more noble and heroic figure as a member of various superhero groups such as the Starforce, United Front and Annihilators. He was married to the Inhuman Crystal, a princess of the Inhuman Royal Family."),
            
            Villian(image: "img_villan_thanos", name: "Thanos", powerScore: 5, description: "Thanos is a fictional supervillain appearing in American comic books published by Marvel Comics. The character was created by writer-artist Jim Starlin, and made his first appearance in The Invincible Iron Man #55 (cover dated February 1973). Thanos is one of the most powerful villains in the Marvel Universe and has clashed with many heroes including the Avengers, the Guardians of the Galaxy, the Fantastic Four, and the X-Men."),
            
            Villian(image: "img_villan_ultron", name: "Ultron", powerScore: 4, description: "Ultron is a fictional supervillain appearing in American comic books published by Marvel Comics. A self-aware and highly intelligent robot created by Hank Pym, the character is usually depicted as a dark reflection of his creator and harbors a strong grudge against him. Ultron's goal to destroy humanity has often brought him into conflict with the Avengers, who always managed to thwart and destroy him, but he would return time and time again. While he usually controls a legion of mindless drones known as 'Ultron Sentries' to help him achieve his goals, Ultron has also been part of several supervillain teams. The character is notable for being the first to wield the fictional metal alloy adamantium and creating Vision."),
            
            Villian(image: "img_villan_yon_rogg", name: "Yon Rogg", powerScore: 3, description: "Yon-Rogg is a fictional character appearing in American comic books published by Marvel Comics. He is an alien Kree, a military commander whose weakness is his jealousy of the accomplishments of others and his love for the medic Una. He is sent to supervise the troublesome planet Earth. He is primarily a foe of Captain Marvel, specifically the Carol Danvers version, and was indirectly responsible for her transformation into Ms. Marvel.")
        ]
    }
}
